AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'features/**/*'
MethodLength:
  Max: 30
Metrics/BlockLength:
  AllowedMethods: ['controllers', 'describe', 'context']
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(When|Given|Then)', '(get|post|put)']
Naming/PredicateName:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/Documentation:
  Exclude: ['**/*']
Style/GuardClause:
  Enabled: false

