version: '3.9'
services:

  test_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"

  dev_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - "5434:5432"
